train_ids:
- CORD-test-0000
- CORD-test-0002
- CORD-test-0003
- CORD-test-0004
- CORD-test-0005
- CORD-test-0006
- CORD-test-0007
- CORD-test-0008
- CORD-test-0009
- CORD-test-0010
- CORD-test-0011
- CORD-test-0012
- CORD-test-0013
- CORD-test-0014
- CORD-test-0015
- CORD-test-0017
- CORD-test-0019
- CORD-test-0020
- CORD-test-0021
- CORD-test-0022
- CORD-test-0023
- CORD-test-0024
- CORD-test-0025
- CORD-test-0026
- CORD-test-0027
- CORD-test-0028
- CORD-test-0032
- CORD-test-0033
- CORD-test-0034
- CORD-test-0035
- CORD-test-0036
- CORD-test-0037
- CORD-test-0038
- CORD-test-0039
- CORD-test-0040
- CORD-test-0041
- CORD-test-0042
- CORD-test-0045
- CORD-test-0047
- CORD-test-0048
- CORD-test-0050
- CORD-test-0051
- CORD-test-0053
- CORD-test-0056
- CORD-test-0057
- CORD-test-0059
- CORD-test-0060
- CORD-test-0063
- CORD-test-0064
- CORD-test-0065
- CORD-test-0066
- CORD-test-0067
- CORD-test-0069
- CORD-test-0070
- CORD-test-0071
- CORD-test-0072
- CORD-test-0073
- CORD-test-0074
- CORD-test-0075
- CORD-test-0076
- CORD-test-0079
- CORD-test-0080
- CORD-test-0082
- CORD-test-0084
- CORD-test-0085
- CORD-test-0086
- CORD-test-0087
- CORD-test-0088
- CORD-test-0089
- CORD-test-0090
- CORD-test-0091
- CORD-test-0092
- CORD-test-0095
- CORD-test-0096
- CORD-test-0098
- CORD-test-0099
- CORD-train-0000
- CORD-train-0001
- CORD-train-0002
- CORD-train-0003
- CORD-train-0004
- CORD-train-0005
- CORD-train-0006
- CORD-train-0007
- CORD-train-0009
- CORD-train-0010
- CORD-train-0011
- CORD-train-0012
- CORD-train-0013
- CORD-train-0014
- CORD-train-0017
- CORD-train-0018
- CORD-train-0019
- CORD-train-0020
- CORD-train-0022
- CORD-train-0023
- CORD-train-0024
- CORD-train-0025
- CORD-train-0027
- CORD-train-0029
- CORD-train-0030
- CORD-train-0031
- CORD-train-0032
- CORD-train-0033
- CORD-train-0034
- CORD-train-0035
- CORD-train-0036
- CORD-train-0037
- CORD-train-0039
- CORD-train-0040
- CORD-train-0041
- CORD-train-0042
- CORD-train-0043
- CORD-train-0045
- CORD-train-0046
- CORD-train-0047
- CORD-train-0048
- CORD-train-0049
- CORD-train-0051
- CORD-train-0052
- CORD-train-0053
- CORD-train-0054
- CORD-train-0055
- CORD-train-0056
- CORD-train-0057
- CORD-train-0061
- CORD-train-0062
- CORD-train-0063
- CORD-train-0064
- CORD-train-0065
- CORD-train-0067
- CORD-train-0068
- CORD-train-0069
- CORD-train-0070
- CORD-train-0071
- CORD-train-0072
- CORD-train-0073
- CORD-train-0075
- CORD-train-0076
- CORD-train-0077
- CORD-train-0078
- CORD-train-0079
- CORD-train-0080
- CORD-train-0081
- CORD-train-0082
- CORD-train-0083
- CORD-train-0084
- CORD-train-0085
- CORD-train-0086
- CORD-train-0087
- CORD-train-0088
- CORD-train-0089
- CORD-train-0090
- CORD-train-0091
- CORD-train-0092
- CORD-train-0094
- CORD-train-0096
- CORD-train-0097
- CORD-train-0098
- CORD-train-0099
- CORD-train-0101
- CORD-train-0102
- CORD-train-0104
- CORD-train-0105
- CORD-train-0106
- CORD-train-0107
- CORD-train-0108
- CORD-train-0109
- CORD-train-0110
- CORD-train-0111
- CORD-train-0112
- CORD-train-0113
- CORD-train-0114
- CORD-train-0116
- CORD-train-0117
- CORD-train-0118
- CORD-train-0119
- CORD-train-0121
- CORD-train-0122
- CORD-train-0123
- CORD-train-0124
- CORD-train-0125
- CORD-train-0126
- CORD-train-0127
- CORD-train-0130
- CORD-train-0131
- CORD-train-0132
- CORD-train-0133
- CORD-train-0134
- CORD-train-0135
- CORD-train-0136
- CORD-train-0137
- CORD-train-0138
- CORD-train-0139
- CORD-train-0140
- CORD-train-0141
- CORD-train-0142
- CORD-train-0143
- CORD-train-0144
- CORD-train-0145
- CORD-train-0148
- CORD-train-0149
- CORD-train-0150
- CORD-train-0152
- CORD-train-0153
- CORD-train-0154
- CORD-train-0155
- CORD-train-0156
- CORD-train-0157
- CORD-train-0158
- CORD-train-0159
- CORD-train-0161
- CORD-train-0162
- CORD-train-0165
- CORD-train-0166
- CORD-train-0167
- CORD-train-0168
- CORD-train-0171
- CORD-train-0172
- CORD-train-0173
- CORD-train-0174
- CORD-train-0176
- CORD-train-0177
- CORD-train-0178
- CORD-train-0179
- CORD-train-0180
- CORD-train-0181
- CORD-train-0182
- CORD-train-0183
- CORD-train-0184
- CORD-train-0185
- CORD-train-0186
- CORD-train-0188
- CORD-train-0189
- CORD-train-0191
- CORD-train-0193
- CORD-train-0194
- CORD-train-0195
- CORD-train-0196
- CORD-train-0199
- CORD-train-0200
- CORD-train-0202
- CORD-train-0203
- CORD-train-0204
- CORD-train-0205
- CORD-train-0207
- CORD-train-0208
- CORD-train-0209
- CORD-train-0210
- CORD-train-0211
- CORD-train-0212
- CORD-train-0214
- CORD-train-0215
- CORD-train-0216
- CORD-train-0217
- CORD-train-0218
- CORD-train-0219
- CORD-train-0220
- CORD-train-0221
- CORD-train-0222
- CORD-train-0223
- CORD-train-0224
- CORD-train-0228
- CORD-train-0230
- CORD-train-0232
- CORD-train-0233
- CORD-train-0234
- CORD-train-0235
- CORD-train-0236
- CORD-train-0237
- CORD-train-0238
- CORD-train-0239
- CORD-train-0240
- CORD-train-0241
- CORD-train-0242
- CORD-train-0243
- CORD-train-0244
- CORD-train-0245
- CORD-train-0247
- CORD-train-0248
- CORD-train-0249
- CORD-train-0250
- CORD-train-0251
- CORD-train-0252
- CORD-train-0254
- CORD-train-0255
- CORD-train-0257
- CORD-train-0258
- CORD-train-0259
- CORD-train-0260
- CORD-train-0261
- CORD-train-0263
- CORD-train-0264
- CORD-train-0265
- CORD-train-0266
- CORD-train-0268
- CORD-train-0271
- CORD-train-0273
- CORD-train-0274
- CORD-train-0275
- CORD-train-0276
- CORD-train-0277
- CORD-train-0278
- CORD-train-0279
- CORD-train-0280
- CORD-train-0281
- CORD-train-0282
- CORD-train-0284
- CORD-train-0285
- CORD-train-0286
- CORD-train-0288
- CORD-train-0290
- CORD-train-0291
- CORD-train-0292
- CORD-train-0294
- CORD-train-0295
- CORD-train-0297
- CORD-train-0298
- CORD-train-0299
- CORD-train-0301
- CORD-train-0302
- CORD-train-0303
- CORD-train-0304
- CORD-train-0305
- CORD-train-0306
- CORD-train-0307
- CORD-train-0308
- CORD-train-0309
- CORD-train-0310
- CORD-train-0312
- CORD-train-0314
- CORD-train-0317
- CORD-train-0319
- CORD-train-0320
- CORD-train-0322
- CORD-train-0323
- CORD-train-0324
- CORD-train-0326
- CORD-train-0327
- CORD-train-0328
- CORD-train-0329
- CORD-train-0330
- CORD-train-0332
- CORD-train-0333
- CORD-train-0334
- CORD-train-0335
- CORD-train-0337
- CORD-train-0338
- CORD-train-0341
- CORD-train-0342
- CORD-train-0343
- CORD-train-0344
- CORD-train-0346
- CORD-train-0348
- CORD-train-0349
- CORD-train-0350
- CORD-train-0353
- CORD-train-0356
- CORD-train-0357
- CORD-train-0358
- CORD-train-0359
- CORD-train-0360
- CORD-train-0361
- CORD-train-0362
- CORD-train-0363
- CORD-train-0365
- CORD-train-0368
- CORD-train-0369
- CORD-train-0370
- CORD-train-0371
- CORD-train-0372
- CORD-train-0373
- CORD-train-0376
- CORD-train-0377
- CORD-train-0378
- CORD-train-0379
- CORD-train-0381
- CORD-train-0382
- CORD-train-0383
- CORD-train-0385
- CORD-train-0386
- CORD-train-0387
- CORD-train-0388
- CORD-train-0390
- CORD-train-0391
- CORD-train-0392
- CORD-train-0393
- CORD-train-0394
- CORD-train-0395
- CORD-train-0396
- CORD-train-0397
- CORD-train-0401
- CORD-train-0402
- CORD-train-0404
- CORD-train-0406
- CORD-train-0407
- CORD-train-0408
- CORD-train-0409
- CORD-train-0410
- CORD-train-0411
- CORD-train-0412
- CORD-train-0413
- CORD-train-0414
- CORD-train-0415
- CORD-train-0416
- CORD-train-0418
- CORD-train-0419
- CORD-train-0420
- CORD-train-0421
- CORD-train-0423
- CORD-train-0424
- CORD-train-0427
- CORD-train-0428
- CORD-train-0429
- CORD-train-0431
- CORD-train-0432
- CORD-train-0433
- CORD-train-0434
- CORD-train-0436
- CORD-train-0438
- CORD-train-0439
- CORD-train-0440
- CORD-train-0441
- CORD-train-0443
- CORD-train-0444
- CORD-train-0446
- CORD-train-0447
- CORD-train-0448
- CORD-train-0449
- CORD-train-0451
- CORD-train-0452
- CORD-train-0454
- CORD-train-0455
- CORD-train-0456
- CORD-train-0457
- CORD-train-0459
- CORD-train-0460
- CORD-train-0462
- CORD-train-0463
- CORD-train-0464
- CORD-train-0466
- CORD-train-0467
- CORD-train-0470
- CORD-train-0471
- CORD-train-0472
- CORD-train-0474
- CORD-train-0476
- CORD-train-0477
- CORD-train-0478
- CORD-train-0479
- CORD-train-0480
- CORD-train-0481
- CORD-train-0484
- CORD-train-0485
- CORD-train-0486
- CORD-train-0487
- CORD-train-0488
- CORD-train-0489
- CORD-train-0490
- CORD-train-0492
- CORD-train-0493
- CORD-train-0494
- CORD-train-0495
- CORD-train-0496
- CORD-train-0497
- CORD-train-0498
- CORD-train-0499
- CORD-train-0500
- CORD-train-0501
- CORD-train-0502
- CORD-train-0503
- CORD-train-0504
- CORD-train-0505
- CORD-train-0506
- CORD-train-0508
- CORD-train-0509
- CORD-train-0511
- CORD-train-0512
- CORD-train-0513
- CORD-train-0515
- CORD-train-0517
- CORD-train-0518
- CORD-train-0519
- CORD-train-0520
- CORD-train-0522
- CORD-train-0523
- CORD-train-0524
- CORD-train-0526
- CORD-train-0527
- CORD-train-0529
- CORD-train-0530
- CORD-train-0531
- CORD-train-0533
- CORD-train-0534
- CORD-train-0535
- CORD-train-0536
- CORD-train-0537
- CORD-train-0538
- CORD-train-0539
- CORD-train-0543
- CORD-train-0544
- CORD-train-0545
- CORD-train-0546
- CORD-train-0548
- CORD-train-0549
- CORD-train-0551
- CORD-train-0552
- CORD-train-0553
- CORD-train-0554
- CORD-train-0555
- CORD-train-0557
- CORD-train-0558
- CORD-train-0559
- CORD-train-0560
- CORD-train-0561
- CORD-train-0562
- CORD-train-0564
- CORD-train-0565
- CORD-train-0566
- CORD-train-0568
- CORD-train-0569
- CORD-train-0571
- CORD-train-0572
- CORD-train-0574
- CORD-train-0576
- CORD-train-0577
- CORD-train-0578
- CORD-train-0579
- CORD-train-0580
- CORD-train-0581
- CORD-train-0582
- CORD-train-0583
- CORD-train-0584
- CORD-train-0586
- CORD-train-0589
- CORD-train-0590
- CORD-train-0591
- CORD-train-0593
- CORD-train-0594
- CORD-train-0595
- CORD-train-0596
- CORD-train-0597
- CORD-train-0600
- CORD-train-0601
- CORD-train-0602
- CORD-train-0603
- CORD-train-0604
- CORD-train-0606
- CORD-train-0607
- CORD-train-0609
- CORD-train-0610
- CORD-train-0611
- CORD-train-0612
- CORD-train-0613
- CORD-train-0614
- CORD-train-0615
- CORD-train-0616
- CORD-train-0617
- CORD-train-0618
- CORD-train-0619
- CORD-train-0620
- CORD-train-0621
- CORD-train-0622
- CORD-train-0623
- CORD-train-0624
- CORD-train-0626
- CORD-train-0627
- CORD-train-0630
- CORD-train-0631
- CORD-train-0633
- CORD-train-0634
- CORD-train-0635
- CORD-train-0636
- CORD-train-0637
- CORD-train-0639
- CORD-train-0640
- CORD-train-0641
- CORD-train-0643
- CORD-train-0644
- CORD-train-0648
- CORD-train-0650
- CORD-train-0651
- CORD-train-0652
- CORD-train-0653
- CORD-train-0654
- CORD-train-0655
- CORD-train-0657
- CORD-train-0658
- CORD-train-0659
- CORD-train-0660
- CORD-train-0661
- CORD-train-0663
- CORD-train-0664
- CORD-train-0666
- CORD-train-0667
- CORD-train-0668
- CORD-train-0669
- CORD-train-0670
- CORD-train-0672
- CORD-train-0673
- CORD-train-0676
- CORD-train-0677
- CORD-train-0681
- CORD-train-0684
- CORD-train-0685
- CORD-train-0686
- CORD-train-0687
- CORD-train-0688
- CORD-train-0690
- CORD-train-0691
- CORD-train-0692
- CORD-train-0693
- CORD-train-0694
- CORD-train-0695
- CORD-train-0696
- CORD-train-0697
- CORD-train-0698
- CORD-train-0699
- CORD-train-0708
- CORD-train-0709
- CORD-train-0710
- CORD-train-0712
- CORD-train-0713
- CORD-train-0716
- CORD-train-0717
- CORD-train-0718
- CORD-train-0719
- CORD-train-0720
- CORD-train-0722
- CORD-train-0723
- CORD-train-0726
- CORD-train-0727
- CORD-train-0728
- CORD-train-0730
- CORD-train-0731
- CORD-train-0732
- CORD-train-0733
- CORD-train-0736
- CORD-train-0737
- CORD-train-0738
- CORD-train-0741
- CORD-train-0742
- CORD-train-0744
- CORD-train-0745
- CORD-train-0746
- CORD-train-0747
- CORD-train-0748
- CORD-train-0749
- CORD-train-0750
- CORD-train-0751
- CORD-train-0752
- CORD-train-0754
- CORD-train-0756
- CORD-train-0757
- CORD-train-0758
- CORD-train-0759
- CORD-train-0760
- CORD-train-0763
- CORD-train-0765
- CORD-train-0766
- CORD-train-0767
- CORD-train-0771
- CORD-train-0773
- CORD-train-0774
- CORD-train-0779
- CORD-train-0780
- CORD-train-0781
- CORD-train-0782
- CORD-train-0783
- CORD-train-0784
- CORD-train-0785
- CORD-train-0786
- CORD-train-0787
- CORD-train-0788
- CORD-train-0790
- CORD-train-0791
- CORD-train-0792
- CORD-train-0793
- CORD-train-0794
- CORD-train-0795
- CORD-train-0796
- CORD-train-0797
- CORD-train-0798
- CORD-validation-0000
- CORD-validation-0001
- CORD-validation-0002
- CORD-validation-0003
- CORD-validation-0004
- CORD-validation-0005
- CORD-validation-0006
- CORD-validation-0007
- CORD-validation-0008
- CORD-validation-0009
- CORD-validation-0010
- CORD-validation-0011
- CORD-validation-0012
- CORD-validation-0014
- CORD-validation-0015
- CORD-validation-0016
- CORD-validation-0017
- CORD-validation-0018
- CORD-validation-0020
- CORD-validation-0021
- CORD-validation-0023
- CORD-validation-0024
- CORD-validation-0028
- CORD-validation-0029
- CORD-validation-0030
- CORD-validation-0032
- CORD-validation-0033
- CORD-validation-0034
- CORD-validation-0035
- CORD-validation-0036
- CORD-validation-0037
- CORD-validation-0038
- CORD-validation-0039
- CORD-validation-0041
- CORD-validation-0042
- CORD-validation-0043
- CORD-validation-0044
- CORD-validation-0045
- CORD-validation-0046
- CORD-validation-0048
- CORD-validation-0049
- CORD-validation-0050
- CORD-validation-0051
- CORD-validation-0052
- CORD-validation-0053
- CORD-validation-0054
- CORD-validation-0055
- CORD-validation-0056
- CORD-validation-0058
- CORD-validation-0059
- CORD-validation-0060
- CORD-validation-0061
- CORD-validation-0062
- CORD-validation-0063
- CORD-validation-0065
- CORD-validation-0066
- CORD-validation-0067
- CORD-validation-0068
- CORD-validation-0069
- CORD-validation-0074
- CORD-validation-0076
- CORD-validation-0077
- CORD-validation-0078
- CORD-validation-0079
- CORD-validation-0081
- CORD-validation-0082
- CORD-validation-0084
- CORD-validation-0085
- CORD-validation-0086
- CORD-validation-0087
- CORD-validation-0088
- CORD-validation-0090
- CORD-validation-0091
- CORD-validation-0092
- CORD-validation-0093
- CORD-validation-0094
- CORD-validation-0096
- CORD-validation-0097
- CORD-validation-0098
test_ids:
- CORD-test-0001
- CORD-test-0016
- CORD-test-0018
- CORD-test-0029
- CORD-test-0030
- CORD-test-0031
- CORD-test-0043
- CORD-test-0044
- CORD-test-0046
- CORD-test-0049
- CORD-test-0052
- CORD-test-0054
- CORD-test-0055
- CORD-test-0058
- CORD-test-0061
- CORD-test-0062
- CORD-test-0068
- CORD-test-0077
- CORD-test-0078
- CORD-test-0081
- CORD-test-0083
- CORD-test-0093
- CORD-test-0094
- CORD-test-0097
- CORD-train-0008
- CORD-train-0015
- CORD-train-0016
- CORD-train-0021
- CORD-train-0026
- CORD-train-0028
- CORD-train-0038
- CORD-train-0044
- CORD-train-0050
- CORD-train-0058
- CORD-train-0059
- CORD-train-0060
- CORD-train-0066
- CORD-train-0074
- CORD-train-0093
- CORD-train-0095
- CORD-train-0100
- CORD-train-0103
- CORD-train-0115
- CORD-train-0120
- CORD-train-0128
- CORD-train-0129
- CORD-train-0146
- CORD-train-0147
- CORD-train-0151
- CORD-train-0160
- CORD-train-0163
- CORD-train-0164
- CORD-train-0169
- CORD-train-0170
- CORD-train-0175
- CORD-train-0187
- CORD-train-0190
- CORD-train-0192
- CORD-train-0197
- CORD-train-0198
- CORD-train-0201
- CORD-train-0206
- CORD-train-0213
- CORD-train-0225
- CORD-train-0226
- CORD-train-0227
- CORD-train-0229
- CORD-train-0231
- CORD-train-0246
- CORD-train-0253
- CORD-train-0256
- CORD-train-0262
- CORD-train-0267
- CORD-train-0269
- CORD-train-0270
- CORD-train-0272
- CORD-train-0283
- CORD-train-0287
- CORD-train-0289
- CORD-train-0293
- CORD-train-0296
- CORD-train-0300
- CORD-train-0311
- CORD-train-0313
- CORD-train-0315
- CORD-train-0316
- CORD-train-0318
- CORD-train-0321
- CORD-train-0325
- CORD-train-0331
- CORD-train-0336
- CORD-train-0339
- CORD-train-0340
- CORD-train-0345
- CORD-train-0347
- CORD-train-0351
- CORD-train-0352
- CORD-train-0354
- CORD-train-0355
- CORD-train-0364
- CORD-train-0366
- CORD-train-0367
- CORD-train-0374
- CORD-train-0375
- CORD-train-0380
- CORD-train-0384
- CORD-train-0389
- CORD-train-0398
- CORD-train-0399
- CORD-train-0400
- CORD-train-0403
- CORD-train-0405
- CORD-train-0417
- CORD-train-0422
- CORD-train-0425
- CORD-train-0426
- CORD-train-0430
- CORD-train-0435
- CORD-train-0437
- CORD-train-0442
- CORD-train-0445
- CORD-train-0450
- CORD-train-0453
- CORD-train-0458
- CORD-train-0461
- CORD-train-0465
- CORD-train-0468
- CORD-train-0469
- CORD-train-0473
- CORD-train-0475
- CORD-train-0482
- CORD-train-0483
- CORD-train-0491
- CORD-train-0507
- CORD-train-0510
- CORD-train-0514
- CORD-train-0516
- CORD-train-0521
- CORD-train-0525
- CORD-train-0528
- CORD-train-0532
- CORD-train-0540
- CORD-train-0541
- CORD-train-0542
- CORD-train-0547
- CORD-train-0550
- CORD-train-0556
- CORD-train-0563
- CORD-train-0567
- CORD-train-0570
- CORD-train-0573
- CORD-train-0575
- CORD-train-0585
- CORD-train-0587
- CORD-train-0588
- CORD-train-0592
- CORD-train-0598
- CORD-train-0599
- CORD-train-0605
- CORD-train-0608
- CORD-train-0625
- CORD-train-0628
- CORD-train-0629
- CORD-train-0632
- CORD-train-0638
- CORD-train-0642
- CORD-train-0645
- CORD-train-0646
- CORD-train-0647
- CORD-train-0649
- CORD-train-0656
- CORD-train-0662
- CORD-train-0665
- CORD-train-0671
- CORD-train-0674
- CORD-train-0675
- CORD-train-0678
- CORD-train-0679
- CORD-train-0680
- CORD-train-0682
- CORD-train-0683
- CORD-train-0689
- CORD-train-0700
- CORD-train-0701
- CORD-train-0702
- CORD-train-0703
- CORD-train-0704
- CORD-train-0705
- CORD-train-0706
- CORD-train-0707
- CORD-train-0711
- CORD-train-0714
- CORD-train-0715
- CORD-train-0721
- CORD-train-0724
- CORD-train-0725
- CORD-train-0729
- CORD-train-0734
- CORD-train-0735
- CORD-train-0739
- CORD-train-0740
- CORD-train-0743
- CORD-train-0753
- CORD-train-0755
- CORD-train-0761
- CORD-train-0762
- CORD-train-0764
- CORD-train-0768
- CORD-train-0769
- CORD-train-0770
- CORD-train-0772
- CORD-train-0775
- CORD-train-0776
- CORD-train-0777
- CORD-train-0778
- CORD-train-0789
- CORD-train-0799
- CORD-validation-0013
- CORD-validation-0019
- CORD-validation-0022
- CORD-validation-0025
- CORD-validation-0026
- CORD-validation-0027
- CORD-validation-0031
- CORD-validation-0040
- CORD-validation-0047
- CORD-validation-0057
- CORD-validation-0064
- CORD-validation-0070
- CORD-validation-0071
- CORD-validation-0072
- CORD-validation-0073
- CORD-validation-0075
- CORD-validation-0080
- CORD-validation-0083
- CORD-validation-0089
- CORD-validation-0095
- CORD-validation-0099
